[gpu_hosts]
server1 ansible_host=149.28.118.43
server2 ansible_host=108.61.203.48

[gpu_hosts:vars]
ansible_python_interpreter=/usr/bin/python3
# Override per-user: ansible_user, ansible_ssh_private_key_file
# e.g. ansible-playbook host-setup.yml -u myuser --private-key ~/.ssh/my_key
# or set ANSIBLE_REMOTE_USER env var
