cluster_name = "mi300x-cluster"

[controller]
listen_addr = "[::]:6817"
state_dir = "/var/spool/spur"

[scheduler]
plugin = "backfill"
interval_secs = 1
max_jobs_per_cycle = 10000
fairshare_halflife_days = 14

[accounting]
host = "localhost:6819"

[auth]
plugin = "none"

[[partitions]]
name = "gpu"
default = true
state = "UP"
nodes = "mi300,mi300-2"
max_time = "7-00:00:00"
default_time = "1:00:00"
min_nodes = 1
priority_tier = 1

[[nodes]]
names = "mi300"
cpus = 256
memory_mb = 2321924
gres = ["gpu:mi300x:8"]

[[nodes]]
names = "mi300-2"
cpus = 256
memory_mb = 2321904
gres = ["gpu:mi300x:8"]

[network]
wg_enabled = false
agent_port = 6818

[logging]
level = "info"
format = "text"
